### ISSUE TITLE
Original URL pages not formatting properly

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/resbaz-2016-02-01#15]
@tjdett I just noticed that the webpages look fine when using the new URL, e.g.
https://2016-02-01.resbaz.com/
https://2016-02-01.resbaz.com/melbourne/

But the formatting is all messed up if you view the original URL, e.g.
http://resbaz.github.io/resbaz-2016-02-01/
http://resbaz.github.io/resbaz-2016-02-01/melbourne

This is bit of a problem because if you go to https://2016-02-01.resbaz.com/ and click on the Melbourne pin on the map, it will take you to http://resbaz.github.io/resbaz-2016-02-01/melbourne

**Comment by katieannemills** [comment]
I can fix these links tonight - will that sort this out, or are there other places pointing to the old links?

**Comment by tjdett** [comment]
@DamienIrving The reason for this is in `_config.yml`, which relies on knowing the base domain and URL: https://github.com/resbaz/resbaz-2016-02-01/compare/7a8f0b0d7256576e9b7a4fa3d194474a00596cc4...7681131

Unfortunately it can't work in both locations if the links are [absolute paths using `{{site.baseurl}}`](https://github.com/resbaz/resbaz-2016-02-01/blob/gh-pages/_includes/head.html#L15). We could change the templates to use relative paths for CSS, which would remove the problem for now, but it would crop back up the moment you had a "foo/bar.html" page.

Best solution is to change the map, as I believe Bill is suggesting.

**Comment by katieannemills** [comment]
ok, looks fixed to me - let me know if there's still problems (also see #16)
