### ISSUE TITLE
no logo

### ISSUE THREAD

**Issue by katieannemills** [resbaz/resbaz-2016-02-01#2]
The resbaz logo doesn't currently appear anywhere on the site - @DamienIrving, do you have an appropriately sized logo?

**Comment by DamienIrving** [comment]
@BillMills I added some logos in #4 - will they do the job?

Should we use one of the nice photos from Flickr as the background image? (i.e. replace the green panel that is there now)

**Comment by katieannemills** [comment]
Re: photo: sounds good! Might need a semitransparent wash to make sure the text is still legible, but that's no problem.
