### ISSUE TITLE
Embedding gitter in the main site

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/resbaz-2016-02-01#7]
@BillMills Sidecar is a new feature that gitter has launched which allows you to embed the feed in your website (a bit like twitter feeds, I'm assuming). Should we try and embed it in the main resbaz website?
https://sidecar.gitter.im/

**Comment by katieannemills** [comment]
I'm super impressed, this is one of the slickest widgets I've ever seen.

**Comment by DamienIrving** [comment]
@BillMills Do you think we should embed the Gitter feed next to the Twitter feed in the "contact ResBaz" part of the website?

**Comment by katieannemills** [comment]
We could do - but I dunno, is that actually better than the pop-over? The pop-over has the advantage of being orthogonal to the rest of the layout - no wondering if things will break on whatever resolution. I also like that the 'join chat' button follows you around, makes it stick out a bit. I dunno, I'm mostly ambivalent on this - if people have a burning desire for an explicit embed, we can do that.

**Comment by DamienIrving** [comment]
Actually, no, you're right. The pop-over is much better!
