### ISSUE TITLE
Where to host this site?

### ISSUE THREAD

**Issue by DamienIrving** [resbaz/resbaz-2016-02-01#8]
Should this repo actually be hosted on the resbaz github account? 

e.g. we could have something like http://resbaz.github.io/resbaz-2016-02-01  /  github.com/resbaz/resbaz-2016-02-01 to distinguish from future events

I think Flanders is going to purchase resbaz.org or something like that, so then we could have that URL point to the latest github.io site (instructions on how to do that [here](https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/))

**Comment by katieannemills** [comment]
Yes - this will definitely migrate to a more agnostic location; it's only under my account right now as we develop things.

(Speaking of, one day this weekend is blocked off for me to respond to all outstanding issues so we can ship by Monday as agreed - get all comments in!)

**Comment by tjdett** [comment]
My current plan is for the site to remain hosted on GitHub Pages (pull-requests FTW!) and to have [CloudFlare manage the DNS & HTTPS support](https://www.benburwell.com/posts/configuring-cloudflare-universal-ssl/). I'll do email redirection using [Mailgun](https://simplyian.com/2015/01/07/Hacking-GMail-to-use-custom-domains-for-free/), so after that we can fill in the (currently blank) email link.

This approach will also be good if we want to put a link shortener on the same domain, as [CloudFlare can cache redirects](https://support.cloudflare.com/hc/en-us/articles/200168326-Are-301-and-302-redirects-cached-by-CloudFlare-) to reduce traffic, so it shouldn't require a particularly powerful server/hosting environment.

**Comment by DamienIrving** [comment]
@BillMills I've just invited you to be an owner of the [resbaz github repo](https://github.com/resbaz) so that you can do the necessary git-fu to migrate the site across to a new repo called https://github.com/resbaz/resbaz-2016-02-01 (once that repo is up we can add the key people from Melbourne, Auckland, etc as collaborators so they can hack their own pages). @tjdett can then do his thing so that https://resbaz.info (or whatever we decide for the URL) points at http://resbaz.github.io/resbaz-2016-02-01/.

**Comment by katieannemills** [comment]
@DamienIrving great! I think the easiest thing to do here, will be for @pkaroly to PR me with her recent changes, get that settled, then transfer my repo to `resbaz-2016-02-01` as you suggest.

**Comment by katieannemills** [comment]
alright, we're ready to transfer - but I can't transfer this repo while the resbaz org still has a fork of it (not allowed to have two forks of the same repo in the same account). @DamienIrving @pkaroly please make sure everything you want to keep from resbaz-site is merged back into my fork, then delete your fork so I can transfer ownership to resbaz.

**Comment by pkaroly** [comment]
I've deleted it

**Comment by katieannemills** [comment]
Ok, all done - @DamienIrving, would recommend against giving everyone with a site commit access to this repo; people should be forking & PRing, so that we don't have to spend time cleaning up engineering oopsies. A core team (you me @pkaroly @tjdett) should do fine - I'm happy to be on deck for reviewing all PRs.
